version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    container_name: map-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: map-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

